// ezx bootstrap examples/bootstrap/config-builder.js
// Declarative config builder (ezx.config): replaces multiline template
// strings with structured JS objects and a fluent builder. One agnostic API
// renders key=value, INI sections, and table/matrix formats.
//
//	const { config } = require("ezx");
//
//  1. config.build({ properties: [...] })  -> flat key=value (postgresql.conf)
//  2. config.build({ rows: [...] })        -> table/matrix   (pg_hba.conf)
//  3. config.build({ sections: {...} })    -> INI sections   (pgbackrest.conf)
//  4. config.builder()                     -> fluent builder with setIf/setFlag
//                                            for conditional configs
const { config, env, log } = require("ezx");

log.info("=== config builder example ===");

// 1. Flat key=value with auto value formatting (numbers/units stay bare,
//    strings are single-quoted).
const postgresql = config.build({
  comment: "PostgreSQL configuration generated by container",
  separator: " = ",
  valueFormat: "auto",
  properties: [
    ["listen_addresses", "*"],
    ["port", 5432],
    ["shared_buffers", "256MB"],
    ["max_connections", 100],
    ["timezone", "UTC"],
    ["log_statement", "ddl"],
  ],
});

// 2. Table / matrix (2D array), column-aligned — pg_hba.conf.
const pgHba = config.build({
  comment: "PostgreSQL Host Based Authentication configuration",
  rows: [
    ["local", "all", "postgres", "trust"],
    ["local", "all", "all", "md5"],
    ["host", "all", "all", "0.0.0.0/0", "md5"],
    ["host", "all", "all", "::/0", "md5"],
  ],
});

// 3. INI sections — pgbackrest.conf. Sections and keys can be map objects
//    (sorted for determinism) or arrays of [key, value] pairs (insertion order).
const pgbackrest = config.build({
  comment: "pgBackRest configuration generated by container",
  separator: "=",
  sections: {
    global: {
      "repo1-retention-full": 2,
      "log-level-console": "info",
      "log-path": "/opt/containers/backup/log",
      "archive-async": "y",
    },
    default: {
      "pg1-path": "/opt/containers/data",
      "pg1-port": 5432,
      "pg1-user": "postgres",
    },
  },
});

// 4. Fluent builder for conditional configs — setIf skips empty values,
//    setFlag emits "=y" only when true.
const b = config.builder({ separator: "=", valueFormat: "none" });
b.comment("Conditional service config");
const srv = b.section("server");
srv.set("port", 8080);
srv.setIf("host", "localhost");
srv.setIf("token", ""); // skipped (empty)
srv.setFlag("tls", true); // tls=y
srv.setFlag("debug", false); // skipped
b.blank();
b.comment("Runtime overrides");
b.setIf("extra", env.get("CONFIG_EXTRA", ""));
log.info("--- postgresql.conf ---\n%s", postgresql);
log.info("--- pg_hba.conf ---\n%s", pgHba);
log.info("--- pgbackrest.conf ---\n%s", pgbackrest);
log.info("--- conditional.ini ---\n%s", b.build());

log.info("=== config builder example complete ===");
