// config.js — declarative config generation for the PostgreSQL container.
// Produces the postgresql.conf, pg_hba.conf, pgbackrest.conf, patroni.yml,
// sshd_config, and pgbouncer.ini files via ezx FileProvision rules consumed by
// the database node (init/03-config in the original entrypoint).
const { env, fs, yaml, config } = require("ezx");
const {
	PGDATA,
	PGBACKUP,
	PGRUN,
	PG_USER,
	PG_GROUP,
	PG_PORT,
	PG_TZ,
	STANZA,
	PATRONI_ENABLE,
	PGBACKREST_ENABLE,
	PGBOUNCER_ENABLE,
	PGBOUNCER_LISTEN_ADDR,
	PGBOUNCER_LISTEN_PORT,
	PGBOUNCER_AUTH_TYPE,
	PGBOUNCER_ADMIN_USERS,
	PGBOUNCER_STATS_USERS,
	PGBOUNCER_POOL_MODE,
	PGBOUNCER_MAX_CLIENT_CONN,
	PGBOUNCER_DEFAULT_POOL_SIZE,
	POSTGRES_CONF,
	PG_HBA,
	PGBACKREST_CONF,
	PATRONI_CONF,
	SSHD_CONF,
	PGBOUNCER_INI,
} = require("./env");

// postgresql.conf: declarative skeleton with env-driven port/timezone.
const postgresqlConfTemplate = config.build({
	comment: "PostgreSQL configuration generated by container",
	separator: " = ",
	valueFormat: "none",
	properties: [
		["listen_addresses", "'*'"],
		["port", PG_PORT],
		["unix_socket_directories", "'" + PGRUN + "'"],
		["max_connections", "100"],
		["shared_buffers", "256MB"],
		["effective_cache_size", "1GB"],
		["maintenance_work_mem", "64MB"],
		["work_mem", "4MB"],
		["wal_level", "replica"],
		["archive_mode", "off"],
		["archive_command", "''"],
		["log_line_prefix", "'%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '"],
		["log_statement", "'ddl'"],
		["log_duration", "on"],
		["log_min_duration_statement", "1000"],
		["ssl", "off"],
		["password_encryption", "scram-sha-256"],
		["random_page_cost", "1.1"],
		["effective_io_concurrency", "200"],
		["autovacuum", "on"],
		["autovacuum_max_workers", "3"],
		["autovacuum_naptime", "20s"],
		["timezone", "'" + PG_TZ + "'"],
		["lc_messages", "'C'"],
		["lc_monetary", "'C'"],
		["lc_numeric", "'C'"],
		["lc_time", "'C'"],
		["# include_dir '/opt/containers/config/custom'", ""],
	],
});

// pg_hba.conf: default authentication rules as a 2D matrix.
const pgHbaTemplate = config.build({
	comment: "PostgreSQL Host Based Authentication configuration",
	rows: [
		["local", "all", "postgres", "trust"],
		["local", "all", "all", "md5"],
		["host", "all", "all", "0.0.0.0/0", "md5"],
		["host", "all", "all", "::/0", "md5"],
	],
});

// pgBackRest config: domain-specific env mapping (REPO_* -> repo1-*, snake to
// kebab, plus truthy flags -> "=y"). Not expressible as a generic NameTransform.
function backupStandby(value) {
	switch ((value || "").toLowerCase()) {
		case "y":
		case "yes":
		case "1":
		case "on":
		case "true":
			return "y";
		case "prefer":
			return "prefer";
		case "n":
		case "no":
		case "0":
		case "off":
		case "false":
			return "n";
		default:
			return "";
	}
}

function pgbackrestConfig() {
	const repoType = env.get(
		"PGBACKREST_REPO_TYPE",
		env.get("PGBACKREST_REPO1_TYPE", "posix"),
	);
	const repoPath = env.get(
		"PGBACKREST_REPO_PATH",
		env.get("PGBACKREST_REPO1_PATH"),
	);

	const b = config.builder({ separator: "=", valueFormat: "none" });

	// [global]
	b.comment("pgBackRest configuration generated by container");
	const global = b.section("global");
	global.set(
		"repo1-retention-full",
		env.get(
			"PGBACKREST_REPO_RETENTION_FULL",
			env.get("PGBACKREST_REPO1_RETENTION_FULL", "2"),
		),
	);
	global.set(
		"repo1-retention-diff",
		env.get(
			"PGBACKREST_REPO_RETENTION_DIFF",
			env.get("PGBACKREST_REPO1_RETENTION_DIFF", "6"),
		),
	);
	global.set("log-level-console", "info");
	global.set("log-level-file", "debug");
	global.set("log-path", PGBACKUP + "/log");
	global.set("lock-path", PGBACKUP + "/lock");
	global.set("spool-path", PGBACKUP + "/spool");
	global.setFromEnv("PGBACKREST_REPO_RETENTION_FULL_TYPE", "repo1-retention-full-type");
	global.setFromEnv("PGBACKREST_PROCESS_MAX", "process-max");
	global.setFlag("archive-async", env.bool("PGBACKREST_ARCHIVE_ASYNC"));
	global.setFromEnv("PGBACKREST_REPO_COMPRESSION", "repo1-compression");
	global.setFlag("sparse-table", env.bool("PGBACKREST_SPARSE_TABLE"));
	global.setFromEnv("PGBACKREST_COMPRESS_LEVEL", "compress-level");
	global.setFromEnv("PGBACKREST_COMPRESS_LEVEL_NETWORK", "compress-level-network");
	global.setFromEnv("PGBACKREST_BUFFER_SIZE", "buffer-size");
	global.setFromEnv("PGBACKREST_IO_TIMEOUT", "io-timeout");
	global.setFromEnv("PGBACKREST_DB_TIMEOUT", "db-timeout");
	global.setFromEnv("PGBACKREST_PROTOCOL_TIMEOUT", "protocol-timeout");
	global.setFromEnv("PGBACKREST_REPO_CIPHER_TYPE", "repo1-cipher-type");
	global.setFromEnv("PGBACKREST_REPO_CIPHER_PASS", "repo1-cipher-pass");
	global.setFlag("repo1-hardlink", env.bool("PGBACKREST_REPO_HARDLINK"));
	global.setFlag("repo1-symlink", env.bool("PGBACKREST_REPO_SYMLINK"));
	global.setFromEnv("PGBACKREST_REPO_RETENTION_ARCHIVE", "repo1-retention-archive");
	global.setFromEnv("PGBACKREST_REPO_RETENTION_ARCHIVE_TYPE", "repo1-retention-archive-type");
	global.setFromEnv("PGBACKREST_REPO_RETENTION_HISTORY", "repo1-retention-history");
	global.setFromEnv("PGBACKREST_ARCHIVE_GET_QUEUE_MAX", "archive-get-queue-max");
	global.setFromEnv("PGBACKREST_ARCHIVE_PUSH_QUEUE_MAX", "archive-push-queue-max");
	global.setFromEnv("PGBACKREST_ARCHIVE_TIMEOUT", "archive-timeout");
	global.setFlag("neutral-umask", env.bool("PGBACKREST_NEUTRAL_UMASK"));
	global.setFromEnv("PGBACKREST_TCP_KEEP_ALIVE_COUNT", "tcp-keep-alive-count");
	global.setFromEnv("PGBACKREST_TCP_KEEP_ALIVE_IDLE", "tcp-keep-alive-idle");
	global.setFromEnv("PGBACKREST_TCP_KEEP_ALIVE_INTERVAL", "tcp-keep-alive-interval");
	global.setFlag("sck-keep-alive", env.bool("PGBACKREST_SCK_KEEP_ALIVE"));
	global.setFromEnv("PGBACKREST_MANIFEST_SAVE_THRESHOLD", "manifest-save-threshold");

	// repo section (no INI header, matches original bare comment+key output)
	b.blank();
	b.comment("Repository 1 configuration");
	b.set("repo1-type", repoType);

	const setOr = (envName, key, fallback) => {
		const v = env.get(envName);
		if (v) b.set(key, v);
		else if (fallback) b.set(key, fallback);
	};

	if (repoType === "posix" || repoType === "filesystem") {
		b.set("repo1-path", repoPath || PGBACKUP);
	} else if (repoType === "s3") {
		const s3 = (envName, key) => {
			const v = env.get("PGBACKREST_REPO_S3_" + envName, env.get("PGBACKREST_REPO1_S3_" + envName));
			if (v) b.set(key, v);
		};
		s3("BUCKET", "repo1-s3-bucket");
		s3("ENDPOINT", "repo1-s3-endpoint");
		s3("REGION", "repo1-s3-region");
		s3("KEY", "repo1-s3-key");
		s3("KEY_SECRET", "repo1-s3-key-secret");
		s3("URI_STYLE", "repo1-s3-uri-style");
		s3("PORT", "repo1-s3-port");
		s3("STORAGE_CLASS", "repo1-s3-storage-class");
		s3("TOKEN", "repo1-s3-token");
		s3("CA_FILE", "repo1-s3-ca-file");
		s3("CA_PATH", "repo1-s3-ca-path");
		s3("BUCKET_REGION", "repo1-s3-bucket-region");
		s3("ENDPOINT_FLEXIBLE", "repo1-s3-endpoint-flexible");
		s3("KMS_KEY_ID", "repo1-s3-kms-key-id");
		s3("SSE_CUSTOMER_KEY", "repo1-s3-sse-customer-key");
		s3("ROLE", "repo1-s3-role");
		s3("KEY_TYPE", "repo1-s3-key-type");
		const verifyTls = env.get("PGBACKREST_REPO_S3_VERIFY_TLS");
		if (verifyTls) b.set("repo1-s3-verify-tls", ["true", "TRUE", "1", "y", "Y"].includes(verifyTls) ? "y" : "n");
		if (env.bool("PGBACKREST_REPO_S3_REQUESTER_PAYS")) b.set("repo1-s3-requester-pays", "y");
		b.set("repo1-path", repoPath || "/pgbackrest");
	} else if (repoType === "gcs") {
		const gcs = (envName, key) => {
			const v = env.get("PGBACKREST_REPO_GCS_" + envName, env.get("PGBACKREST_REPO1_GCS_" + envName));
			if (v) b.set(key, v);
		};
		gcs("BUCKET", "repo1-gcs-bucket");
		gcs("ENDPOINT", "repo1-gcs-endpoint");
		gcs("KEY", "repo1-gcs-key");
		gcs("KEY_TYPE", "repo1-gcs-key-type");
		gcs("USER_PROJECT", "repo1-gcs-user-project");
		gcs("ENDPOINT_FLEXIBLE", "repo1-gcs-endpoint-flexible");
		gcs("CA_BUNDLE_FILE", "repo1-gcs-ca-bundle-file");
		gcs("CA_BUNDLE_PATH", "repo1-gcs-ca-bundle-path");
		b.set("repo1-path", repoPath || "/pgbackrest");
	} else if (repoType === "sftp") {
		const sftp = (envName, key) => {
			const v = env.get("PGBACKREST_REPO_SFTP_" + envName, env.get("PGBACKREST_REPO1_SFTP_" + envName));
			if (v) b.set(key, v);
		};
		sftp("HOST", "repo1-sftp-host");
		sftp("HOST_PORT", "repo1-sftp-host-port");
		sftp("HOST_USER", "repo1-sftp-host-user");
		sftp("HOST_FINGERPRINT", "repo1-sftp-host-fingerprint");
		sftp("HOST_KEY_CHECK_TYPE", "repo1-sftp-host-key-check-type");
		sftp("HOST_KEY_HASH_TYPE", "repo1-sftp-host-key-hash-type");
		sftp("PRIVATE_KEY_FILE", "repo1-sftp-private-key-file");
		sftp("PRIVATE_KEY_PASSPHRASE", "repo1-sftp-private-key-passphrase");
		sftp("PUBLIC_KEY_FILE", "repo1-sftp-public-key-file");
		const knownHosts = env.get("PGBACKREST_REPO_SFTP_KNOWN_HOSTS", env.get("PGBACKREST_REPO1_SFTP_KNOWN_HOSTS"));
		for (const kh of (knownHosts || "").split(/[, ]+/).filter(Boolean)) b.set("repo1-sftp-known-host", kh);
		const hostUser = env.get("PGBACKREST_REPO_SFTP_HOST_USER", env.get("PGBACKREST_REPO1_SFTP_HOST_USER"));
		b.set("repo1-path", repoPath || (hostUser ? "/home/" + hostUser + "/pgbackrest" : "/pgbackrest"));
	} else if (repoType === "azure") {
		const az = (envName, key) => {
			const v = env.get("PGBACKREST_REPO_AZURE_" + envName, env.get("PGBACKREST_REPO1_AZURE_" + envName));
			if (v) b.set(key, v);
		};
		az("ACCOUNT", "repo1-azure-account");
		az("CONTAINER", "repo1-azure-container");
		az("ENDPOINT", "repo1-azure-endpoint");
		az("KEY", "repo1-azure-key");
		az("KEY_TYPE", "repo1-azure-key-type");
		az("URI_STYLE", "repo1-azure-uri-style");
		b.set("repo1-path", repoPath || "/pgbackrest");
	} else {
		b.set("repo1-path", repoPath || "/pgbackrest");
	}

	// Unified storage options (repo1-storage-*)
	for (const [envName, key] of [
		["PGBACKREST_REPO_STORAGE_HOST", "repo1-storage-host"],
		["PGBACKREST_REPO_STORAGE_PORT", "repo1-storage-port"],
		["PGBACKREST_REPO_STORAGE_CA_FILE", "repo1-storage-ca-file"],
		["PGBACKREST_REPO_STORAGE_CA_PATH", "repo1-storage-ca-path"],
		["PGBACKREST_REPO_STORAGE_UPLOAD_CHUNK_SIZE", "repo1-storage-upload-chunk-size"],
	]) {
		b.setFromEnv(envName, key);
	}
	const storageVerify = env.get("PGBACKREST_REPO_STORAGE_VERIFY_TLS");
	if (storageVerify) b.set("repo1-storage-verify-tls", ["true", "TRUE", "1", "y", "Y"].includes(storageVerify) ? "y" : "n");
	for (const tag of (env.get("PGBACKREST_REPO_STORAGE_TAG") || "").split(/[, ]+/).filter(Boolean)) {
		b.set("repo1-storage-tag", tag);
	}

	// Remote repository host options (repo1-host-*)
	for (const [envName, key] of [
		["PGBACKREST_REPO_HOST", "repo1-host"],
		["PGBACKREST_REPO_HOST_PORT", "repo1-host-port"],
		["PGBACKREST_REPO_HOST_USER", "repo1-host-user"],
		["PGBACKREST_REPO_HOST_TYPE", "repo1-host-type"],
		["PGBACKREST_REPO_HOST_KEY_FILE", "repo1-host-key-file"],
		["PGBACKREST_REPO_HOST_CA_FILE", "repo1-host-ca-file"],
		["PGBACKREST_REPO_HOST_CA_PATH", "repo1-host-ca-path"],
		["PGBACKREST_REPO_HOST_CERT_FILE", "repo1-host-cert-file"],
		["PGBACKREST_REPO_HOST_CONFIG", "repo1-host-config"],
		["PGBACKREST_REPO_HOST_CONFIG_PATH", "repo1-host-config-path"],
	]) {
		b.setFromEnv(envName, key);
	}

	// standby backup
	const standby = backupStandby(env.get("PGBACKREST_BACKUP_STANDBY"));
	if (standby) b.set("backup-standby", standby);

	// stanza
	b.blank();
	const stanza = b.section(STANZA);
	stanza.set("pg1-path", PGDATA);
	stanza.set("pg1-port", PG_PORT);
	stanza.set("pg1-user", PG_USER);
	stanza.set("pg1-socket-path", PGRUN);
	stanza.setFromEnv("PGBACKREST_PG_DATABASE", "pg1-database");
	stanza.setFromEnv("PGBACKREST_PG_HOST", "pg1-host");
	stanza.setFromEnv("PGBACKREST_PG_HOST_PORT", "pg1-host-port");
	stanza.setFromEnv("PGBACKREST_PG_HOST_USER", "pg1-host-user");
	stanza.setFromEnv("PGBACKREST_PG_HOST_TYPE", "pg1-host-type");
	stanza.setFromEnv("PGBACKREST_PG_HOST_KEY_FILE", "pg1-host-key-file");
	stanza.setFromEnv("PGBACKREST_PG_HOST_CA_FILE", "pg1-host-ca-file");
	stanza.setFromEnv("PGBACKREST_PG_HOST_CA_PATH", "pg1-host-ca-path");
	stanza.setFromEnv("PGBACKREST_PG_HOST_CERT_FILE", "pg1-host-cert-file");
	stanza.setFromEnv("PGBACKREST_PG_HOST_CONFIG", "pg1-host-config");
	stanza.setFromEnv("PGBACKREST_PG_HOST_CONFIG_PATH", "pg1-host-config-path");
	stanza.setFromEnv("PGBACKREST_PG_HOST_CMD", "pg1-host-cmd");
	stanza.setFromEnv("PGBACKREST_PASSWORD", "pg1-password");

	// pg2-* SSH standby block (PGBACKREST_PRIMARY_PATH enables SSH mode)
	const primaryPath = env.get("PGBACKREST_PRIMARY_PATH");
	if (primaryPath) {
		const primaryHost = env.get("PGBACKREST_PRIMARY_HOST", env.get("PRIMARY_HOST"));
		if (primaryHost) {
			b.blank();
			b.comment("Primary connection for standby backup (SSH mode)");
			b.set("pg2-host", primaryHost);
			b.set("pg2-host-port", env.get("PGBACKREST_PRIMARY_SSH_PORT", "22"));
			b.set("pg2-host-user", env.get("PGBACKREST_PRIMARY_SSH_USER", "postgres"));
			b.set("pg2-path", primaryPath);
			b.set("pg2-port", env.get("PGBACKREST_PRIMARY_PORT", env.get("PRIMARY_PORT", "5432")));
			b.set("pg2-user", env.get("PGBACKREST_PRIMARY_USER", PG_USER));
			const sshKey = env.get("PGBACKREST_PRIMARY_SSH_KEY_FILE", "/home/postgres/.ssh/id_rsa");
			if (sshKey && fs.exists(sshKey)) b.set("pg2-host-key-file", sshKey);
			for (const [envName, key] of [
				["PGBACKREST_PRIMARY_HOST_CA_FILE", "pg2-host-ca-file"],
				["PGBACKREST_PRIMARY_HOST_CA_PATH", "pg2-host-ca-path"],
				["PGBACKREST_PRIMARY_HOST_CERT_FILE", "pg2-host-cert-file"],
				["PGBACKREST_PRIMARY_HOST_CONFIG", "pg2-host-config"],
				["PGBACKREST_PRIMARY_HOST_CONFIG_PATH", "pg2-host-config-path"],
			]) {
				b.setFromEnv(envName, key);
			}
			const knownHostsFile = env.get("PGBACKREST_PRIMARY_SSH_KNOWN_HOSTS");
			if (knownHostsFile && fs.exists(knownHostsFile)) b.set("pg2-host-known-hosts-file", knownHostsFile);
			// Auto-enable backup-standby when SSH mode configured and user hasn't set it
			if (!env.get("PGBACKREST_BACKUP_STANDBY") && !standby) b.set("backup-standby", "y");
		}
	}

	return b.build();
}

// sshd_config template (mirrors the bash 05-sshd.sh heredoc).
const sshdTemplate = config.build({
	separator: " ",
	properties: [
		["Port", "22"],
		["AddressFamily", "any"],
		["ListenAddress", ["0.0.0.0", "::"]],
		["Protocol", "2"],
		["HostKey", ["/run/ssh/ssh_host_rsa_key", "/run/ssh/ssh_host_ecdsa_key", "/run/ssh/ssh_host_ed25519_key"]],
		["SyslogFacility", "AUTH"],
		["LogLevel", "INFO"],
		["PermitRootLogin", "no"],
		["PubkeyAuthentication", "yes"],
		["PasswordAuthentication", "no"],
		["PermitEmptyPasswords", "no"],
		["ChallengeResponseAuthentication", "no"],
		["UsePAM", "yes"],
		["X11Forwarding", "no"],
		["PrintMotd", "no"],
		["AcceptEnv", "LANG LC_*"],
		["Subsystem", "sftp /usr/lib/openssh/sftp-server"],
		["AllowUsers", "postgres"],
	],
});

// pgbouncer.ini: generated declaratively from the PGBOUNCER_* defaults,
// replacing the bash sed placeholder substitution. PGBOUNCER_CONFIG_* overrides
// are applied on top via the set-property FileProvision below.
function pgbouncerConfig() {
	const b = config.builder({ separator: " = " });
	b.section("databases").set("*", "host=localhost port=" + PG_PORT);
	b.blank();
	const p = b.section("pgbouncer");
	p.set("listen_addr", PGBOUNCER_LISTEN_ADDR);
	p.set("listen_port", PGBOUNCER_LISTEN_PORT);
	p.set("unix_socket_dir", PGRUN);
	p.set("auth_type", PGBOUNCER_AUTH_TYPE);
	p.set("auth_file", "/etc/pgbouncer/userlist.txt");
	p.set("admin_users", PGBOUNCER_ADMIN_USERS);
	p.set("stats_users", PGBOUNCER_STATS_USERS);
	p.set("pool_mode", PGBOUNCER_POOL_MODE);
	p.set("max_client_conn", PGBOUNCER_MAX_CLIENT_CONN);
	p.set("default_pool_size", PGBOUNCER_DEFAULT_POOL_SIZE);
	p.set("logfile", "/var/log/pgbouncer/pgbouncer.log");
	p.set("pidfile", "/var/run/pgbouncer/pgbouncer.pid");
	p.set("user", "postgres");
	return b.build();
}

// Patroni etcd hosts, normalized to host:port strings.
function etcdHosts() {
	const hosts = env
		.get(
			"PATRONI_ETCD_HOSTS",
			env.get("ETCD_HOSTS", env.get("ETCD_HOST", "localhost")),
		)
		.replace(/;/g, ",")
		.split(",")
		.map((s) => s.trim())
		.filter(Boolean);
	const port = env.get("ETCD_PORT", "2379");
	return hosts.map((h) => (h.includes(":") ? h : h + ":" + port));
}

// Patroni YAML, built structurally from a JS object (no template-string
// concatenation or manual indentation). yaml.build serializes it.
const hostname = env.get("HOSTNAME", "");
const restConnectHost = env.get(
	"PATRONI_REST_CONNECT_HOST",
	env.get("PATRONI_REST_HOST", hostname || "0.0.0.0"),
);
const pgConnectHost = env.get(
	"POSTGRESQL_CONNECT_HOST",
	env.get("POSTGRESQL_LISTEN_HOST", hostname || "0.0.0.0"),
);
const restPort = env.get("PATRONI_REST_PORT", "8008");

// Patroni synchronous-mode knobs: PATRONI_SYNCHRONOUS_* with fallback to
// REPLICATION_SYNCHRONOUS_MODE (03-config.sh:664-691).
let syncMode = env.get("PATRONI_SYNCHRONOUS_MODE", "");
const syncStrict = env.get("PATRONI_SYNCHRONOUS_MODE_STRICT", "");
const syncType = env.get("PATRONI_SYNCHRONOUS_MODE_TYPE", "").toLowerCase();
const syncTimeout = env.get("PATRONI_SYNCHRONOUS_MODE_TIMEOUT", "");
if (
	!syncMode &&
	!syncStrict &&
	!syncType &&
	!syncTimeout &&
	env.get("REPLICATION_SYNCHRONOUS_MODE", "true") === "true"
) {
	syncMode = "true";
}

// CITUS enable detection (03-config.sh:640-649): gate on CITUS_ENABLE.
const citusEnabled = env.bool("CITUS_ENABLE");

// PG_HBA_ADD_* merged into the Patroni pg_hba list with dedup.
const patroniPgHba = [
	"local all postgres trust",
	"local all all md5",
	`host replication ${env.get("REPLICATION_USER", "replicator")} 0.0.0.0/0 md5`,
	"host all all 0.0.0.0/0 md5",
];
for (const kv of Object.entries(env.all()).sort(([a], [b]) => a.localeCompare(b))) {
	if (/^PG_HBA_ADD_([0-9]+)$/.test(kv[0]) && !patroniPgHba.includes(kv[1])) {
		patroniPgHba.push(kv[1]);
	}
}

const pgbackrestArchive =
	PGBACKREST_ENABLE && env.bool("PGBACKREST_ARCHIVE_ENABLE", true);
const archiveCommand = pgbackrestArchive
	? `env -u PGBACKREST_ENABLE -u PGBACKREST_AUTO_ENABLE pgbackrest --config=/etc/pgbackrest.conf --stanza=${STANZA} archive-push %p` +
	  (env.get("PGBACKREST_ARCHIVE_COMMAND_EXTRA") || "")
	: "";

const patroniYaml = yaml.build({
	scope: env.get("PATRONI_SCOPE", "postgres-cluster"),
	name: env.get("PATRONI_NAME", "postgres-node-1"),
	restapi: {
		listen: `${env.get("PATRONI_REST_HOST", "0.0.0.0")}:${restPort}`,
		connect_address: `${restConnectHost}:${restPort}`,
	},
	etcd3: {
		hosts: etcdHosts(),
	},
	watchdog: {
		mode: env.get("PATRONI_WATCHDOG_MODE", "off"),
		device: env.get("PATRONI_WATCHDOG_DEVICE", "/dev/watchdog"),
		safety_margin: env.int("PATRONI_WATCHDOG_SAFETY_MARGIN", 5),
	},
	bootstrap: {
		dcs: {
			ttl: env.int("PATRONI_TTL", 30),
			loop_wait: env.int("PATRONI_LOOP_WAIT", 10),
			retry_timeout: env.int("PATRONI_RETRY_TIMEOUT", 10),
			maximum_lag_on_failover: env.int("PATRONI_MAX_LAG", 1048576),
			...syncMode ? { synchronous_mode: syncMode } : {},
			...syncStrict ? { synchronous_mode_strict: syncStrict } : {},
			...syncType ? { synchronous_mode_type: syncType } : {},
			...syncTimeout ? { synchronous_mode_timeout: syncTimeout } : {},
			postgresql: {
				use_pg_rewind: env.bool("PATRONI_USE_PG_REWIND", true),
				use_slots: env.bool("PATRONI_USE_SLOTS", true),
				parameters: {
					wal_level: "replica",
					hot_standby: "on",
					logging_collector: "on",
					max_wal_senders: env.int("PATRONI_MAX_WAL_SENDERS", 10),
					max_replication_slots: env.int("PATRONI_MAX_REPLICATION_SLOTS", 10),
					wal_keep_segments: env.int("PATRONI_WAL_KEEP_SEGMENTS", 8),
					archive_mode: pgbackrestArchive ? "on" : "off",
					archive_timeout: env.get("ARCHIVE_TIMEOUT", "1800s"),
					archive_command: archiveCommand,
					...citusEnabled ? { shared_preload_libraries: "citus" } : {},
				},
				pg_hba: patroniPgHba,
				...citusEnabled ? { citus: { group: env.int("CITUS_GROUP", 0), database: env.get("CITUS_DATABASE", "postgres") } } : {},
			},
		},
	},
	postgresql: {
		listen: `${env.get("POSTGRESQL_LISTEN_HOST", "0.0.0.0")}:${PG_PORT}`,
		connect_address: `${pgConnectHost}:${PG_PORT}`,
		data_dir: PGDATA,
		config_dir: PGDATA,
		user: "postgres",
		pgpass: "/tmp/pgpass",
		authentication: {
			replication: {
				username: env.get("REPLICATION_USER", "replicator"),
				password: env.get("REPLICATION_PASSWORD", "replicator_password"),
			},
			superuser: {
				username: PG_USER,
				password: env.get("POSTGRES_PASSWORD", "postgres_password"),
			},
		},
		parameters: {
			unix_socket_directories: PGRUN,
			timezone: PG_TZ,
		},
		...citusEnabled ? { shared_preload_libraries: "citus" } : {},
	},
	...citusEnabled
		? {
				citus: {
					group: env.int("CITUS_GROUP", 0),
					database: env.get("CITUS_DATABASE", "postgres"),
					port: env.int("POSTGRESQL_PORT", 5432),
				},
			}
		: {},
});

// Declarative FileProvision rules consumed by the database node.
const postgresFiles = [
	// postgresql.conf: always overwrite the initdb-generated default with the
	// container template (mirrors bash 03-config.sh), then env overrides
	// (smart-quoted). initdb creates a default postgresql.conf first, so
	// createOnly would skip this and postgres would run without
	// unix_socket_directories = PGRUN (listening on /tmp instead).
	{
		path: POSTGRES_CONF,
		operations: [{ type: "replace", value: postgresqlConfTemplate }],
	},
	{
		path: POSTGRES_CONF,
		operations: [
			{
				type: "set-property",
				fromEnvPattern: "^POSTGRESQL_CONFIG_(.+)$",
				nameTransform: "lower",
				pattern: "^\\s*#?\\s*${name}\\s*=.*",
				value: "${name} = ${value}",
				valueFormat: "auto",
			},
			{
				type: "set-property",
				fromEnv: "POSTGRESQL_SHARED_BUFFERS",
				pattern: "^shared_buffers\\s*=.*",
				value: "shared_buffers = ${value}",
				valueFormat: "auto",
			},
			{
				type: "set-property",
				fromEnv: "POSTGRESQL_MAX_CONNECTIONS",
				pattern: "^max_connections\\s*=.*",
				value: "max_connections = ${value}",
				valueFormat: "auto",
			},
			{
				type: "set-property",
				fromEnv: "POSTGRESQL_LISTEN_ADDRESSES",
				pattern: "^listen_addresses\\s*=.*",
				value: "listen_addresses = ${value}",
				valueFormat: "auto",
			},
			{
				type: "set-property",
				fromEnv: "POSTGRESQL_WORK_MEM",
				pattern: "^work_mem\\s*=.*",
				value: "work_mem = ${value}",
				valueFormat: "auto",
			},
			{
				type: "set-property",
				fromEnv: "POSTGRESQL_MAINTENANCE_WORK_MEM",
				pattern: "^maintenance_work_mem\\s*=.*",
				value: "maintenance_work_mem = ${value}",
				valueFormat: "auto",
			},
			{
				type: "set-property",
				fromEnv: "POSTGRESQL_UNIX_SOCKET_DIRECTORIES",
				pattern: "^unix_socket_directories\\s*=.*",
				value: "unix_socket_directories = ${value}",
				valueFormat: "auto",
			},
			{
				type: "set-property",
				fromEnv: "POSTGRESQL_LOG_STATEMENT",
				pattern: "^log_statement\\s*=.*",
				value: "log_statement = ${value}",
				valueFormat: "auto",
			},
			{
				type: "set-property",
				fromEnv: "POSTGRESQL_LOG_DURATION",
				pattern: "^log_duration\\s*=.*",
				value: "log_duration = ${value}",
				valueFormat: "auto",
			},
			{
				type: "set-property",
				fromEnv: "POSTGRESQL_TIMEZONE",
				pattern: "^timezone\\s*=.*",
				value: "timezone = ${value}",
				valueFormat: "auto",
			},
		],
	},
	// pgBackRest archiving (non-Patroni): enable archive_mode + archive_command
	// + archive_timeout in postgresql.conf when pgBackRest is on (mirrors
	// 04-backup.sh:enable_archiving). Patroni manages its own archiving.
	{
		path: POSTGRES_CONF,
		when: { name: "PGBACKREST_ENABLE", value: "true" },
		operations: [
			{
				type: "set-property",
				pattern: "^\\s*#?\\s*archive_mode\\s*=.*",
				value: "archive_mode = on",
				valueFormat: "raw",
			},
			{
				type: "set-property",
				pattern: "^\\s*#?\\s*archive_command\\s*=.*",
				value:
					"archive_command = '" +
					"env -u PGBACKREST_ENABLE -u PGBACKREST_AUTO_ENABLE pgbackrest --config=/etc/pgbackrest.conf --stanza=" +
					STANZA +
					" archive-push %p " +
					(env.get("PGBACKREST_ARCHIVE_COMMAND_EXTRA") || "") +
					"'",
				valueFormat: "raw",
			},
			{
				type: "set-property",
				pattern: "^\\s*#?\\s*archive_timeout\\s*=.*",
				value: "archive_timeout = " + env.get("ARCHIVE_TIMEOUT", "1800s"),
				valueFormat: "raw",
			},
		],
	},
	// Native HA replication settings (HA_MODE=native), mirrors
	// 03-config.sh:apply_native_ha_config.
	{
		path: POSTGRES_CONF,
		when: { name: "HA_MODE", value: "native" },
		operations: (() => {
			const ops = [
				{ type: "set-property", pattern: "^listen_addresses\\s*=.*", value: "listen_addresses = '*'", valueFormat: "raw" },
				{ type: "set-property", pattern: "^wal_level\\s*=.*", value: "wal_level = replica", valueFormat: "raw" },
				{ type: "set-property", pattern: "^max_wal_senders\\s*=.*", value: "max_wal_senders = 10", valueFormat: "raw" },
				{ type: "set-property", pattern: "^max_replication_slots\\s*=.*", value: "max_replication_slots = 10", valueFormat: "raw" },
				{ type: "set-property", pattern: "^wal_keep_size\\s*=.*", value: "wal_keep_size = 256MB", valueFormat: "raw" },
				{ type: "set-property", pattern: "^hot_standby\\s*=.*", value: "hot_standby = on", valueFormat: "raw" },
			];
			// Synchronous replication: on by default; when off, remove the line.
			if (env.get("REPLICATION_SYNCHRONOUS_MODE", "true") === "true") {
				ops.push({
					type: "set-property",
					pattern: "^synchronous_standby_names\\s*=.*",
					value:
						"synchronous_standby_names = '" +
						(env.get("REPLICATION_SYNCHRONOUS_COUNT") && env.get("REPLICATION_SYNCHRONOUS_REPLICAS")
							? "ANY " + env.get("REPLICATION_SYNCHRONOUS_COUNT") + " (" + env.get("REPLICATION_SYNCHRONOUS_REPLICAS") + ")"
							: "*") +
						"'",
					valueFormat: "raw",
				});
			} else {
				ops.push({ type: "remove", pattern: "^synchronous_standby_names\\s*=.*" });
			}
			return ops;
		})(),
	},
	// Replica-specific native HA settings (hot_standby_feedback, standby delays).
	{
		path: POSTGRES_CONF,
		when: { name: "REPLICATION_ROLE", value: "replica" },
		operations: [
			{ type: "set-property", pattern: "^hot_standby_feedback\\s*=.*", value: "hot_standby_feedback = on", valueFormat: "raw" },
			{ type: "set-property", pattern: "^max_standby_streaming_delay\\s*=.*", value: "max_standby_streaming_delay = -1", valueFormat: "raw" },
			{ type: "set-property", pattern: "^max_standby_archive_delay\\s*=.*", value: "max_standby_archive_delay = -1", valueFormat: "raw" },
		],
	},
	// pg_hba.conf: always overwrite the initdb-generated default (mirrors bash
	// 03-config.sh), then external-access + PG_HBA_ADD_*.
	{
		path: PG_HBA,
		operations: [{ type: "replace", value: pgHbaTemplate }],
	},
	{
		path: PG_HBA,
		operations: [
			{
				type: "set-property",
				when: { name: "EXTERNAL_ACCESS_ENABLE", value: "true" },
				pattern: "^host\\s+all\\s+all\\s+0\\.0\\.0\\.0/0.*",
				value:
					"host    all             all             0.0.0.0/0               " +
					env.get("EXTERNAL_ACCESS_METHOD", env.get("POSTGRES_HOST_AUTH_METHOD", "md5")),
			},
			{
				type: "set-property",
				when: { name: "EXTERNAL_ACCESS_ENABLE", value: "true" },
				pattern: "^host\\s+all\\s+all\\s+::/0.*",
				value:
					"host    all             all             ::/0                    " +
					env.get("EXTERNAL_ACCESS_METHOD", env.get("POSTGRES_HOST_AUTH_METHOD", "md5")),
			},
			// When external access is explicitly disabled, remove both host lines.
			{
				type: "remove",
				when: { name: "EXTERNAL_ACCESS_ENABLE", value: "false" },
				pattern: "^host\\s+all\\s+all\\s+(0\\.0\\.0\\.0/0|::/0).*",
			},
			// Native-HA primary replication line.
			{
				type: "ensure",
				when: { name: "HA_MODE", value: "native" },
				value:
					"host    replication        " + env.get("REPLICATION_USER", "replicator") +
					"             0.0.0.0/0               " +
					env.get("REPLICATION_AUTH_METHOD", "scram-sha-256"),
			},
		],
	},
	// PG_HBA_ADD_*: appended after the base rules. Note: dedup of re-applied
	// lines (bash 03-config.sh state-file) is not expressible declaratively in
	// ezx 0.0.1 (ProcessFunc is Go-only); accumulation only matters if PG_HBA_ADD_*
	// changes between container restarts.
	{
		path: PG_HBA,
		operations: [
			{
				type: "append",
				fromEnvPattern: "^PG_HBA_ADD_([0-9]+)$",
				value: "${value}",
			},
		],
	},
	// pgbackrest.conf: generated by JS (domain-specific PGBACKREST_* mapping,
	// e.g. REPO_* -> repo1-*, is not expressible as a generic NameTransform).
	{
		path: PGBACKREST_CONF,
		when: { name: "PGBACKREST_ENABLE", value: "true" },
		operations: [{ type: "replace", value: pgbackrestConfig() }],
	},
	// patroni.yml, conditional on PATRONI_ENABLE.
	{
		path: PATRONI_CONF,
		when: { name: "PATRONI_ENABLE", value: "true" },
		operations: [{ type: "replace", value: patroniYaml }],
	},
	// sshd_config, chmod 644 (mirrors bash 05-sshd.sh).
	{
		path: SSHD_CONF,
		permission: 0o644,
		operations: [{ type: "replace", value: sshdTemplate }],
	},
	// pgbouncer.ini: generate the base config from PGBOUNCER_* defaults, then
	// apply PGBOUNCER_CONFIG_* overrides on top (mirrors the bash template sed +
	// override loop). chown/chmod 600 like bash.
	{
		path: PGBOUNCER_INI,
		when: { name: "PGBOUNCER_ENABLE", value: "true" },
		permission: 0o600,
		owner: "postgres:postgres",
		operations: [
			{ type: "replace", value: pgbouncerConfig() },
			{
				type: "set-property",
				fromEnvPattern: "^PGBOUNCER_CONFIG_(.+)$",
				nameTransform: "lower",
				pattern: "^${name}\\s*=.*",
				value: "${name} = ${value}",
			},
		],
	},
];

module.exports = {
	postgresFiles,
	pgbouncerConfig,
	pgbackrestConfig,
	backupStandby,
	etcdHosts,
	patroniYaml,
};