// config.js — declarative config generation for the PostgreSQL container.
// Produces the postgresql.conf, pg_hba.conf, pgbackrest.conf, patroni.yml,
// sshd_config, and pgbouncer.ini files via ezx FileProvision rules consumed by
// the database node (init/03-config in the original entrypoint).
const { env, yaml, config } = require("ezx");
const {
	PGDATA,
	PGBACKUP,
	PGRUN,
	PG_USER,
	PG_GROUP,
	PG_PORT,
	PG_TZ,
	STANZA,
	PATRONI_ENABLE,
	PGBACKREST_ENABLE,
	PGBOUNCER_ENABLE,
	POSTGRES_CONF,
	PG_HBA,
	PGBACKREST_CONF,
	PATRONI_CONF,
	SSHD_CONF,
	PGBOUNCER_INI,
} = require("./env");

// postgresql.conf: declarative skeleton with env-driven port/timezone.
const postgresqlConfTemplate = config.build({
	comment: "PostgreSQL configuration generated by container",
	separator: " = ",
	valueFormat: "none",
	properties: [
		["listen_addresses", "'*'"],
		["port", PG_PORT],
		["max_connections", "100"],
		["shared_buffers", "256MB"],
		["effective_cache_size", "1GB"],
		["maintenance_work_mem", "64MB"],
		["work_mem", "4MB"],
		["wal_level", "replica"],
		["archive_mode", "off"],
		["archive_command", "''"],
		["log_line_prefix", "'%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '"],
		["log_statement", "'ddl'"],
		["log_duration", "on"],
		["log_min_duration_statement", "1000"],
		["ssl", "off"],
		["password_encryption", "scram-sha-256"],
		["random_page_cost", "1.1"],
		["effective_io_concurrency", "200"],
		["autovacuum", "on"],
		["autovacuum_max_workers", "3"],
		["autovacuum_naptime", "20s"],
		["timezone", "'" + PG_TZ + "'"],
	],
});

// pg_hba.conf: default authentication rules as a 2D matrix.
const pgHbaTemplate = config.build({
	comment: "PostgreSQL Host Based Authentication configuration",
	rows: [
		["local", "all", "postgres", "trust"],
		["local", "all", "all", "md5"],
		["host", "all", "all", "0.0.0.0/0", "md5"],
		["host", "all", "all", "::/0", "md5"],
	],
});

// pgBackRest config: domain-specific env mapping (REPO_* -> repo1-*, snake to
// kebab, plus truthy flags -> "=y"). Not expressible as a generic NameTransform.
function backupStandby(value) {
	switch ((value || "").toLowerCase()) {
		case "y":
		case "yes":
		case "1":
		case "on":
		case "true":
			return "y";
		case "prefer":
			return "prefer";
		case "n":
		case "no":
		case "0":
		case "off":
		case "false":
			return "n";
		default:
			return "";
	}
}

function pgbackrestConfig() {
	const repoType = env.get(
		"PGBACKREST_REPO_TYPE",
		env.get("PGBACKREST_REPO1_TYPE", "posix"),
	);
	const repoPath = env.get(
		"PGBACKREST_REPO_PATH",
		env.get("PGBACKREST_REPO1_PATH"),
	);

	const b = config.builder({ separator: "=", valueFormat: "none" });

	// [global]
	b.comment("pgBackRest configuration generated by container");
	const global = b.section("global");
	global.set(
		"repo1-retention-full",
		env.get(
			"PGBACKREST_REPO_RETENTION_FULL",
			env.get("PGBACKREST_REPO1_RETENTION_FULL", "2"),
		),
	);
	global.set(
		"repo1-retention-diff",
		env.get(
			"PGBACKREST_REPO_RETENTION_DIFF",
			env.get("PGBACKREST_REPO1_RETENTION_DIFF", "6"),
		),
	);
	global.set("log-level-console", "info");
	global.set("log-level-file", "debug");
	global.set("log-path", PGBACKUP + "/log");
	global.set("lock-path", PGBACKUP + "/lock");
	global.set("spool-path", PGBACKUP + "/spool");
	global.setFromEnv("PGBACKREST_REPO_RETENTION_FULL_TYPE", "repo1-retention-full-type");
	global.setFromEnv("PGBACKREST_PROCESS_MAX", "process-max");
	global.setFlag("archive-async", env.isTruthy("PGBACKREST_ARCHIVE_ASYNC"));
	global.setFromEnv("PGBACKREST_REPO_COMPRESSION", "repo1-compression");

	// repo section (no INI header, matches original bare comment+key output)
	b.blank();
	b.comment("Repository 1 configuration");
	b.set("repo1-type", repoType);
	if (repoType === "posix" || repoType === "filesystem") {
		b.set("repo1-path", repoPath || PGBACKUP);
	} else if (repoType === "s3") {
		b.setFromEnv("PGBACKREST_REPO_S3_BUCKET", "repo1-s3-bucket");
		b.setFromEnv("PGBACKREST_REPO_S3_ENDPOINT", "repo1-s3-endpoint");
		b.setFromEnv("PGBACKREST_REPO_S3_KEY", "repo1-s3-key");
		b.setFromEnv("PGBACKREST_REPO_S3_KEY_SECRET", "repo1-s3-key-secret");
		b.set("repo1-path", repoPath || "/pgbackrest");
	} else if (repoType === "gcs") {
		b.setFromEnv("PGBACKREST_REPO_GCS_BUCKET", "repo1-gcs-bucket");
		b.set("repo1-path", repoPath || "/pgbackrest");
	} else {
		b.set("repo1-path", repoPath || "/pgbackrest");
	}

	// standby backup
	const standby = backupStandby(env.get("PGBACKREST_BACKUP_STANDBY"));
	if (standby) b.set("backup-standby", standby);

	// stanza
	b.blank();
	const stanza = b.section(STANZA);
	stanza.set("pg1-path", PGDATA);
	stanza.set("pg1-port", PG_PORT);
	stanza.set("pg1-user", PG_USER);
	stanza.set("pg1-socket-path", PGRUN);
	stanza.setFromEnv("PGBACKREST_PASSWORD", "pg1-password");
	return b.build();
}

// sshd_config template.
const sshdTemplate = config.build({
	separator: " ",
	properties: [
		["Port", "22"],
		["AddressFamily", "any"],
		["ListenAddress", ["0.0.0.0", "::"]],
		["Protocol", "2"],
		["HostKey", ["/run/ssh/ssh_host_rsa_key", "/run/ssh/ssh_host_ecdsa_key", "/run/ssh/ssh_host_ed25519_key"]],
		["PermitRootLogin", "no"],
		["PubkeyAuthentication", "yes"],
		["PasswordAuthentication", "no"],
		["PermitEmptyPasswords", "no"],
		["UsePAM", "yes"],
		["AllowUsers", "postgres"],
	],
});

// Patroni etcd hosts, normalized to host:port strings.
function etcdHosts() {
	const hosts = env
		.get(
			"PATRONI_ETCD_HOSTS",
			env.get("ETCD_HOSTS", env.get("ETCD_HOST", "localhost")),
		)
		.replace(/;/g, ",")
		.split(",")
		.map((s) => s.trim())
		.filter(Boolean);
	const port = env.get("ETCD_PORT", "2379");
	return hosts.map((h) => (h.includes(":") ? h : h + ":" + port));
}

// Patroni YAML, built structurally from a JS object (no template-string
// concatenation or manual indentation). yaml.build serializes it.
const patroniYaml = yaml.build({
	scope: env.get("PATRONI_SCOPE", "postgres-cluster"),
	name: env.get("PATRONI_NAME", "postgres-node-1"),
	restapi: {
		listen: `${env.get("PATRONI_REST_HOST", "0.0.0.0")}:${env.get("PATRONI_REST_PORT", "8008")}`,
	},
	etcd3: {
		hosts: etcdHosts(),
	},
	bootstrap: {
		dcs: {
			ttl: parseInt(env.get("PATRONI_TTL", "30"), 10),
			loop_wait: parseInt(env.get("PATRONI_LOOP_WAIT", "10"), 10),
			retry_timeout: parseInt(env.get("PATRONI_RETRY_TIMEOUT", "10"), 10),
			maximum_lag_on_failover: parseInt(env.get("PATRONI_MAX_LAG", "1048576"), 10),
			postgresql: {
				parameters: {
					wal_level: "replica",
					hot_standby: "on",
					max_wal_senders: parseInt(env.get("PATRONI_MAX_WAL_SENDERS", "10"), 10),
					max_replication_slots: parseInt(env.get("PATRONI_MAX_REPLICATION_SLOTS", "10"), 10),
					archive_mode: PGBACKREST_ENABLE ? "on" : "off",
					archive_command: PGBACKREST_ENABLE
						? `env -u PGBACKREST_ENABLE pgbackrest --config=/etc/pgbackrest.conf --stanza=${STANZA} archive-push %p`
						: "",
				},
				pg_hba: [
					"local all postgres trust",
					"local all all md5",
					`host replication ${env.get("REPLICATION_USER", "replicator")} 0.0.0.0/0 md5`,
					"host all all 0.0.0.0/0 md5",
				],
			},
		},
	},
	postgresql: {
		listen: `${env.get("POSTGRESQL_LISTEN_HOST", "0.0.0.0")}:${PG_PORT}`,
		data_dir: PGDATA,
		config_dir: PGDATA,
		user: "postgres",
		authentication: {
			replication: {
				username: env.get("REPLICATION_USER", "replicator"),
				password: env.get("REPLICATION_PASSWORD", "replicator_password"),
			},
			superuser: {
				username: PG_USER,
				password: env.get("POSTGRES_PASSWORD", "postgres_password"),
			},
		},
		parameters: {
			unix_socket_directories: PGRUN,
			timezone: PG_TZ,
		},
	},
});

// Declarative FileProvision rules consumed by the database node.
const postgresFiles = [
	// postgresql.conf: create once if missing, then env overrides (smart-quoted).
	{
		path: POSTGRES_CONF,
		createOnly: true,
		operations: [{ type: "replace", value: postgresqlConfTemplate }],
	},
	{
		path: POSTGRES_CONF,
		operations: [
			{
				type: "set-property",
				fromEnvPattern: "^POSTGRESQL_CONFIG_(.+)$",
				nameTransform: "lower",
				pattern: "^\\s*#?\\s*${name}\\s*=.*",
				value: "${name} = ${value}",
				valueFormat: "auto",
			},
			{
				type: "set-property",
				fromEnv: "POSTGRESQL_SHARED_BUFFERS",
				pattern: "^shared_buffers\\s*=.*",
				value: "shared_buffers = ${value}",
				valueFormat: "auto",
			},
			{
				type: "set-property",
				fromEnv: "POSTGRESQL_MAX_CONNECTIONS",
				pattern: "^max_connections\\s*=.*",
				value: "max_connections = ${value}",
				valueFormat: "auto",
			},
			{
				type: "set-property",
				fromEnv: "POSTGRESQL_LISTEN_ADDRESSES",
				pattern: "^listen_addresses\\s*=.*",
				value: "listen_addresses = ${value}",
				valueFormat: "auto",
			},
			{
				type: "set-property",
				fromEnv: "POSTGRESQL_WORK_MEM",
				pattern: "^work_mem\\s*=.*",
				value: "work_mem = ${value}",
				valueFormat: "auto",
			},
		],
	},
	// pg_hba.conf: default once if missing, then external-access + PG_HBA_ADD_*.
	{
		path: PG_HBA,
		createOnly: true,
		operations: [{ type: "replace", value: pgHbaTemplate }],
	},
	{
		path: PG_HBA,
		operations: [
			{
				type: "set-property",
				when: { name: "EXTERNAL_ACCESS_ENABLE", value: "true" },
				pattern: "^host\\s+all\\s+all\\s+0\\.0\\.0\\.0/0.*",
				value:
					"host    all             all             0.0.0.0/0               " +
					env.get("EXTERNAL_ACCESS_METHOD", "md5"),
			},
			{
				type: "append",
				fromEnvPattern: "^PG_HBA_ADD_([0-9]+)$",
				value: "${value}",
			},
		],
	},
	// pgbackrest.conf: generated by JS (domain-specific PGBACKREST_* mapping,
	// e.g. REPO_* -> repo1-*, is not expressible as a generic NameTransform).
	{
		path: PGBACKREST_CONF,
		when: { name: "PGBACKREST_ENABLE", value: "true" },
		operations: [{ type: "replace", value: pgbackrestConfig() }],
	},
	// patroni.yml, conditional on PATRONI_ENABLE.
	{
		path: PATRONI_CONF,
		when: { name: "PATRONI_ENABLE", value: "true" },
		operations: [{ type: "replace", value: patroniYaml }],
	},
	// sshd_config.
	{ path: SSHD_CONF, operations: [{ type: "replace", value: sshdTemplate }] },
	// pgbouncer.ini env sub (only if enabled).
	{
		path: PGBOUNCER_INI,
		when: { name: "PGBOUNCER_ENABLE", value: "true" },
		operations: [
			{
				type: "set-property",
				fromEnvPattern: "^PGBOUNCER_CONFIG_(.+)$",
				nameTransform: "lower",
				pattern: "^${name}\\s*=.*",
				value: "${name} = ${value}",
			},
		],
	},
];

module.exports = {
	postgresFiles,
	pgbackrestConfig,
	backupStandby,
	etcdHosts,
	patroniYaml,
};