// runtime.js — runtime/startup: supervise the database + sidecar process tree
// in a single chain. ezx stays PID 1 and supervises the postgres/patroni root
// and every needParentReady child (stanza/userlist/repl-user init one-shots,
// pgbouncer, sshd, scheduled backups) concurrently, forwarding signals, reaping
// zombies, and draining on SIGTERM. The Patroni role-check runs as a
// scheduler.every JS callback in api.js (no curl child). Scheduled pgBackRest
// backup node-builders are absorbed here from the old backup.js.
const { env, fs, chain, scheduler, shell } = require("ezx");
const {
	PGDATA,
	PGRUN,
	PG_USER,
	PG_GROUP,
	PG_PORT,
	PG_PASS,
	PATRONI_ENABLE,
	PGBOUNCER_ENABLE,
	PGBACKREST_ENABLE,
	PATRONI_CONF,
	PGBOUNCER_INI,
	PGBOUNCER_USERLIST,
	REPL_ROLE,
	REPL_USER,
	REPL_PASSWORD,
	HA_MODE,
	STANZA,
	TIMEOUT,
	PG_READY_MAX_ATTEMPTS,
	PGBACKREST_AUTO,
	PGBACKREST_AUTO_FIRST_INCR_DELAY,
	CITUS_ENABLE,
	CITUS_ROLE,
} = require("./env");
const { postgresFiles } = require("./config");
const { roleCheckNode } = require("./api");

// oneShot — a needParentReady child that runs a command to completion then
// exits (stanza-create, userlist generation, replication-user creation).
function oneShot(name, cmd, opts) {
	const base = {
		binaryPath: "/bin/sh",
		arguments: ["-c", cmd],
		user: PG_USER,
		group: PG_GROUP,
	};
	return Object.assign(
		{ name, needParentReady: true, process: base },
		opts || {},
		{ process: Object.assign(base, (opts && opts.process) || {}) },
	);
}

// userlist-init — query pg_shadow for the postgres password hash and write
// pgbouncer userlist.txt (bash startup.sh:285-302). Kept as a shell pipeline
// child node (needParentReady) because it needs psql stdout captured into a
// file; every interpolated value is quoted with shell.quote.
function userlistInit() {
	if (!PGBOUNCER_ENABLE) return null;
	const pgUser = env.get("POSTGRES_USER", "postgres");
	const pgPass = PG_PASS;
	let cmd;
	if (pgPass) {
		cmd =
			"PGPASSWORD=" +
			shell.quote(pgPass) +
			" psql -v ON_ERROR_STOP=1 -tA -h " +
			shell.quote(PGRUN) +
			" -d postgres -U " +
			shell.quote(pgUser) +
			" -c " +
			shell.quote("SELECT passwd FROM pg_shadow WHERE usename = '" + String(pgUser).replace(/'/g, "''") + "';") +
			" | sed 's/^/\"" + String(pgUser).replace(/"/g, '\\"') + "\" \"/; s/$/\"/'" +
			" > " + PGBOUNCER_USERLIST;
	} else {
		cmd = 'echo "' + pgUser + '" "" > ' + PGBOUNCER_USERLIST;
	}
	cmd += " && chown " + PG_USER + ":" + PG_GROUP + " " + PGBOUNCER_USERLIST + " && chmod 600 " + PGBOUNCER_USERLIST;
	return oneShot("pgbouncer-userlist", cmd);
}

// stanza-init — create/upgrade the pgBackRest stanza once postgres is ready
// (bash startup.sh:initialize_pgbackrest_stanza + cluster.sh modes).
function stanzaInit() {
	if (!PGBACKREST_ENABLE) return null;
	const cmd =
		"if ! pgbackrest --config=/etc/pgbackrest.conf --stanza=" +
		shell.quote(STANZA) +
		" stanza-create; then pgbackrest --config=/etc/pgbackrest.conf --stanza=" +
		shell.quote(STANZA) +
		" stanza-upgrade; fi && pgbackrest --config=/etc/pgbackrest.conf --stanza=" +
		shell.quote(STANZA) +
		" check";
	return oneShot("pgbackrest-stanza-init", cmd, {
		process: { filterEnvPattern: ["^PGBACKREST_"] },
	});
}

// repl-user — create the replication user for native-HA primary (bash
// startup.sh:create_replication_user).
function replUser() {
	if (HA_MODE !== "native" || REPL_ROLE !== "primary" || !REPL_USER) return null;
	if (!REPL_PASSWORD) throw new Error("REPLICATION_PASSWORD required for native-HA primary");
	const pgUser = env.get("POSTGRES_USER", "postgres");
	const cmd =
		"PGPASSWORD=" +
		shell.quote(REPL_PASSWORD) +
		" psql -h 127.0.0.1 -p " +
		PG_PORT +
		" -U " +
		shell.quote(pgUser) +
		" -d postgres -c " +
		shell.quote(
			"DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '" + String(REPL_USER).replace(/'/g, "''") + "') THEN CREATE ROLE " + REPL_USER + " REPLICATION LOGIN PASSWORD '" + String(REPL_PASSWORD).replace(/'/g, "''") + "'; END IF; END $$;",
		);
	return oneShot("replication-user", cmd);
}

// pgbouncerNode — supervised long-running pgbouncer sidecar (restart always).
// The pgbouncer.ini is generated by the postgresFiles FileProvision during
// chain.run (gated on PGBOUNCER_ENABLE), so no existence check here — it runs
// before provisioning and would fail spuriously. Runs pgbouncer in foreground
// (no -d): daemon mode forks and the parent exits 0 immediately, which would
// make ezx restart-loop on the still-held socket.
function pgbouncerNode() {
	if (!PGBOUNCER_ENABLE) return null;
	return {
		name: "pgbouncer",
		needParentReady: true,
		optional: true,
		process: {
			binaryPath: "pgbouncer",
			arguments: [PGBOUNCER_INI],
			user: PG_USER,
			group: PG_GROUP,
		},
		restart: { mode: "always", backoff: 2e9 },
		forwardSignals: ["SIGTERM", "SIGINT", "SIGHUP"],
	};
}

// sshdNode — supervised long-running sshd sidecar on the primary (restart
// always). Gated on REPL_ROLE because this is evaluated at tree-build time,
// before postgres is up; native replicas are never primary. Runs sshd with -D
// (don't daemonize): without it sshd forks into the background and the parent
// exits 0 immediately, making ezx restart-loop on the held port 22.
function sshdNode() {
	if (REPL_ROLE === "replica") return null;
	if (!fs.exists("/usr/sbin/sshd")) return null;
	return {
		name: "sshd",
		needParentReady: true,
		optional: true,
		process: { binaryPath: "/usr/sbin/sshd", arguments: ["-D"] },
		restart: { mode: "always", backoff: 2e9 },
		forwardSignals: ["SIGTERM", "SIGINT", "SIGHUP"],
	};
}

function startSleep() {
	chain.run({
		roots: [
			{
				name: "sleep",
				process: {
					binaryPath: "/bin/sh",
					arguments: ["-c", "while true; do sleep 3600; done"],
				},
				restart: { mode: "always", backoff: 1000 * 1e6 },
			},
		],
	});
}

// Backup flags from env, mirroring the shell scheduler's run_backup (no bash).
function backupFlags(type) {
	const args = [
		"--config=/etc/pgbackrest.conf",
		"--stanza=" + STANZA,
		"backup",
		"--type=" + type,
	];
	const flag = (envName, arg) => {
		if (env.bool(envName)) args.push(arg);
	};
	// Default-true flags: env.bool honors the shell's default-true semantics.
	const flagDefault = (envName, arg, def) => {
		if (env.bool(envName, def)) args.push(arg);
	};
	flag("PGBACKREST_BACKUP_START_FAST", "--start-fast");
	flag("PGBACKREST_BACKUP_STOP_AUTO", "--stop-auto");
	flagDefault("PGBACKREST_BACKUP_VERIFY", "--verify", true);
	flag("PGBACKREST_BACKUP_CHECKSUM_PAGE", "--checksum-page");
	flagDefault("PGBACKREST_BACKUP_ARCHIVE_CHECK", "--archive-check", true);
	flag("PGBACKREST_BACKUP_ARCHIVE_COPY", "--archive-copy");
	flag("PGBACKREST_BACKUP_EXPIRE_AUTO", "--expire-auto");
	flagDefault("PGBACKREST_BACKUP_RESUME", "--resume", true);
	flagDefault(
		"PGBACKREST_BACKUP_ARCHIVE_MISSING_RETRY",
		"--archive-missing-retry",
		true,
	);
	for (const x of (env.get("PGBACKREST_BACKUP_EXCLUDE") || "")
		.split(/[, ]+/)
		.filter(Boolean))
		args.push("--exclude=" + x);
	for (const a of (env.get("PGBACKREST_BACKUP_ANNOTATION") || "")
		.split(/[, ]+/)
		.filter(Boolean))
		args.push("--annotation=" + a);
	return args;
}

// Primary-role gate (postgres-specific, composed from generic probes):
// Patroni REST /master then /leader → 2xx when primary; Citus role env; else
// pg_is_in_recovery()=f via psql. The scheduled node skips ticks while the
// gate fails, so replicas never run backups.
function primaryGate() {
	if (PATRONI_ENABLE) {
		const base = env.get("PATRONI_REST_URL", "http://localhost:8008");
		// A single http probe can only target one URL; /master with a fallback
		// to /leader is expressed as an exec that curls either endpoint.
		return {
			type: "exec",
			exec: [
				"/bin/sh",
				"-c",
				"curl -fs " + base + "/master >/dev/null 2>&1 || curl -fs " + base + "/leader >/dev/null 2>&1",
			],
		};
	}
	if (CITUS_ENABLE) {
		return CITUS_ROLE === "coordinator"
			? { type: "exec", exec: ["true"] }
			: { type: "exec", exec: ["false"] };
	}
	return {
		type: "exec",
		exec: [
			"/bin/sh",
			"-c",
			"PGPASSWORD=" + shell.quote(env.get("POSTGRES_PASSWORD") || "") + " psql -qtAX -U " +
				PG_USER + " -h 127.0.0.1 -p " + PG_PORT + " -d " +
				shell.quote(env.get("POSTGRES_DB", "postgres")) +
				" -c 'select pg_is_in_recovery();' | grep -q f",
		],
	};
}

// A scheduled pgBackRest backup node: ezx runs the node's Process on the cron
// tick, gated on primary-role, and skips duplicate ticks within a minute.
function backupNode(type, defaultCron) {
	return {
		name: "backup-" + type,
		needParentReady: true,
		optional: true,
		process: {
			binaryPath: "pgbackrest",
			arguments: backupFlags(type),
			user: PG_USER,
			group: PG_GROUP,
			// Replace the shell's generate_clean_env_command (env -u PGBACKREST_*).
			filterEnvPattern: ["^PGBACKREST_"],
		},
		scheduler: scheduler.build({
			schedule: {
				expression: env.get(
					"PGBACKREST_AUTO_" + type.toUpperCase() + "_CRON",
					defaultCron,
				),
				timezone: env.get("PGBACKREST_AUTO_TIMEZONE", "UTC"),
			},
			initialDelay: PGBACKREST_AUTO_FIRST_INCR_DELAY * 1e9,
			minInterval: 60e9, // one backup per minute, matching the shell dedup
			// PGBACKREST_AUTO_PRIMARY_ONLY (default true) gates backups on the
			// primary role; set false to also run on replicas (SSH standby).
			gate: env.bool("PGBACKREST_AUTO_PRIMARY_ONLY", true) ? primaryGate() : null,
		}),
	};
}

// Scheduled backup children attached to the postgres node (needParentReady so
// backups start only after the DB is up, replacing PGBACKREST_PARENT_PID).
function backupNodes() {
	if (!PGBACKREST_ENABLE || !PGBACKREST_AUTO) return [];
	return [
		backupNode("full", "0 2 * * *"),
		backupNode("diff", "20 2,8,14,20 * * *"),
		backupNode("incr", "*/15 * * * *"),
	];
}

function startDatabase() {
	const mainProcess = PATRONI_ENABLE
		? {
				binaryPath: "patroni",
				arguments: [PATRONI_CONF],
				user: PG_USER,
				group: PG_GROUP,
			}
		: {
				binaryPath: env.get("POSTGRES_BIN", "postgres"),
				arguments: ["-D", PGDATA],
				user: PG_USER,
				group: PG_GROUP,
			};

	const children = [
		stanzaInit(),
		replUser(),
		userlistInit(),
		pgbouncerNode(),
		sshdNode(),
		roleCheckNode(),
	]
		.concat(backupNodes())
		.filter(Boolean);

	const node = {
		name: PATRONI_ENABLE ? "patroni" : "postgres",
		process: mainProcess,
		files: postgresFiles,
		forwardSignals: ["SIGTERM", "SIGINT", "SIGHUP", "SIGUSR1", "SIGUSR2"],
		shutdown: { timeout: TIMEOUT * 1e9, forceKill: true },
		children,
	};

	// Readiness probe gating needParentReady children (postgres must accept
	// connections before stanza-init/userlist/pgbouncer/sshd start). Mirrors
	// the bash wait_for_postgresql_ready loop. Set unconditionally — node.health
	// (the /readyz HTTP surface) is only wired when EZX_HEALTH_ADDR is set.
	node.readiness = {
		type: "exec",
		exec: ["pg_isready", "-h", PGRUN, "-p", PG_PORT, "-U", PG_USER],
		interval: 1e9,
		timeout: 5e9,
		maxAttempts: PG_READY_MAX_ATTEMPTS,
	};

	const healthAddr = env.get("EZX_HEALTH_ADDR");
	if (healthAddr) {
		node.health = { readyProbe: node.readiness };
		// Backup manual-trigger + role-check routes are registered by
		// api.js:registerOpsRoutes (called from main.js before chain.run).
	}

	chain.run({ roots: [node] });
}

module.exports = {
	startPgbouncer: pgbouncerNode,
	startSshd: sshdNode,
	startSleep,
	startDatabase,
	backupFlags,
	primaryGate,
	backupNode,
	backupNodes,
};
