package scriptmodules

import (
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"

	"github.com/supanadit/ezx/internal/repository"
)

// ConfigModule exposes ezx.config: a format-agnostic config-file builder for
// scripts. It replaces fragile multiline template strings with declarative JS
// objects (config.build) or a fluent builder (config.builder) for conditional
// configs. It supports three line-oriented formats:
//
//   - key-value  (postgresql.conf, sshd_config)   key = value
//   - ini        (pgbackrest.conf, pgbouncer.ini) [section] key=value
//   - table      (pg_hba.conf)                    column 1 | column 2 | ...
//
//	const { config } = require("ezx");
//	const pg = config.build({
//	  comment: "PostgreSQL configuration generated by container",
//	  separator: " = ",
//	  valueFormat: "auto",
//	  properties: {
//	    listen_addresses: "*",
//	    port: "5432",
//	    shared_buffers: "256MB",
//	    timezone: "UTC",
//	  },
//	});
type ConfigModule struct{}

// NewConfigModule returns a ConfigModule. It is stateless.
func NewConfigModule() *ConfigModule {
	return &ConfigModule{}
}

// Build serializes a declarative config spec to a string. The format is
// auto-detected from the spec: Rows -> table, Sections -> ini, Properties ->
// key-value. A header Comment is emitted first. Order of map-backed Properties
// and Sections is sorted for determinism; pass them as an array of [key, value]
// pairs to preserve insertion order. A property whose value is an array emits
// one line per element (for repeating keys like sshd's ListenAddress).
func (m *ConfigModule) Build(spec map[string]any) (string, error) {
	sep := asString(spec["separator"])
	if sep == "" {
		sep = " = "
	}
	vf := asString(spec["valueFormat"])

	b := NewConfigBuilder().WithSeparator(sep).WithValueFormat(vf)

	for _, c := range commentLines(spec["comment"]) {
		b.Comment(c)
	}

	// Table format: a 2D matrix of rows, columns joined by spaces.
	if rows, ok := tableRows(spec["rows"]); ok {
		b.Rows(rows)
		return b.Build(), nil
	}

	// INI format: named sections, each a set of key-value pairs.
	if sections, ok := orderedSections(spec["sections"]); ok {
		for _, sec := range sections {
			s := b.Section(sec.name)
			for _, kv := range sec.pairs {
				for _, line := range splitRepeat(kv.value) {
					s.Set(kv.name, line)
				}
			}
		}
		return b.Build(), nil
	}

	// Key-value format.
	if props, ok := orderedPairs(spec["properties"]); ok {
		for _, kv := range props {
			for _, line := range splitRepeat(kv.value) {
				b.Set(kv.name, line)
			}
		}
	}
	return b.Build(), nil
}

// Builder returns a mutable, fluent config builder. Options may carry
// separator (default " = ") and valueFormat ("none", "quote", "auto").
//
//	const b = config.builder({ separator: "=" });
//	b.comment("pgBackRest configuration");
//	const g = b.section("global");
//	g.set("repo1-retention-full", "2");
//	g.setIf("process-max", env.get("PGBACKREST_PROCESS_MAX"));
//	g.setFlag("archive-async", env.isTruthy("PGBACKREST_ARCHIVE_ASYNC"));
//	b.build();
func (m *ConfigModule) Builder(opts ...map[string]any) *ConfigBuilder {
	o := ConfigOptions{}
	if len(opts) > 0 && opts[0] != nil {
		if v := asString(opts[0]["separator"]); v != "" {
			o.Separator = v
		}
		o.ValueFormat = asString(opts[0]["valueFormat"])
	}
	return NewConfigBuilder().WithOptions(o)
}

// ConfigOptions configures rendering for a ConfigBuilder.
type ConfigOptions struct {
	Separator   string // key-value separator (default " = ")
	ValueFormat string // "none", "quote", or "auto"
}

// ConfigBuilder is a fluent, ordered config builder. Root-level key-value
// lines live in the implicit global scope; Section(name) opens an INI section
// and returns a sub-builder scoped to it. All lines are rendered in insertion
// order, so the builder is ideal for conditional configs.
type ConfigBuilder struct {
	opts        ConfigOptions
	current     string        // active section name for root adds ("" = global)
	entries     []configEntry // ordered output lines
	renderTable bool
}

type configEntry struct {
	kind    configKind
	section string      // section this entry belongs to ("" = global)
	key     string      // key-value key
	value   string      // key-value value (already serialized)
	text    string      // comment text or raw line
	rows    [][]string  // table rows
	hasSect bool        // whether this entry carries an explicit section tag
}

type configKind int

const (
	kindComment configKind = iota
	kindBlank
	kindKeyval
	kindSectionHeader
	kindTable
)

// ConfigSection is a builder scoped to an INI section. Its Set/SetIf/SetFlag
// methods append to the parent builder under the section name.
type ConfigSection struct {
	parent  *ConfigBuilder
	section string
}

// NewConfigBuilder returns a builder with default options.
func NewConfigBuilder() *ConfigBuilder {
	return &ConfigBuilder{opts: ConfigOptions{Separator: " = ", ValueFormat: "none"}}
}

// WithSeparator sets the key-value separator.
func (b *ConfigBuilder) WithSeparator(sep string) *ConfigBuilder {
	if sep != "" {
		b.opts.Separator = sep
	}
	return b
}

// WithValueFormat sets the value format ("none", "quote", "auto").
func (b *ConfigBuilder) WithValueFormat(vf string) *ConfigBuilder {
	b.opts.ValueFormat = vf
	return b
}

// WithOptions merges options onto the builder.
func (b *ConfigBuilder) WithOptions(o ConfigOptions) *ConfigBuilder {
	if o.Separator != "" {
		b.opts.Separator = o.Separator
	}
	if o.ValueFormat != "" {
		b.opts.ValueFormat = o.ValueFormat
	}
	return b
}

// Comment adds a "# text" comment line.
func (b *ConfigBuilder) Comment(text string) *ConfigBuilder {
	b.entries = append(b.entries, configEntry{kind: kindComment, section: b.current, text: text})
	return b
}

// Blank adds an empty separator line.
func (b *ConfigBuilder) Blank() *ConfigBuilder {
	b.entries = append(b.entries, configEntry{kind: kindBlank, section: b.current})
	return b
}

// Set adds a key=value line. An array value emits one line per element
// (repeating keys). Returns the builder for chaining.
func (b *ConfigBuilder) Set(key string, value any) *ConfigBuilder {
	for _, v := range splitRepeat(value) {
		b.entries = append(b.entries, configEntry{
			kind: kindKeyval, section: b.current, key: key,
			value: b.format(key, v),
		})
	}
	return b
}

// SetIf adds a key=value line only when value is non-empty.
func (b *ConfigBuilder) SetIf(key string, value string) *ConfigBuilder {
	if value != "" {
		b.Set(key, value)
	}
	return b
}

// SetFlag adds "key=y" when truthy is true, otherwise skips.
func (b *ConfigBuilder) SetFlag(key string, truthy bool) *ConfigBuilder {
	if truthy {
		b.entries = append(b.entries, configEntry{
			kind: kindKeyval, section: b.current, key: key, value: "y",
		})
	}
	return b
}

// SetFromEnv adds "key=<env value>" only when the env value is non-empty.
func (b *ConfigBuilder) SetFromEnv(envName, key string) *ConfigBuilder {
	return b.SetIf(key, EnvGet(envName))
}

// Section opens an INI [name] section and returns a sub-builder scoped to it.
func (b *ConfigBuilder) Section(name string) *ConfigSection {
	b.entries = append(b.entries, configEntry{kind: kindSectionHeader, section: name, text: name})
	return &ConfigSection{parent: b, section: name}
}

// Rows sets table rows (2D matrix). Overrides any key-value/INI content.
func (b *ConfigBuilder) Rows(rows [][]string) *ConfigBuilder {
	b.renderTable = true
	b.entries = append(b.entries, configEntry{kind: kindTable, rows: rows})
	return b
}

// Build serializes the collected lines to a config string.
func (b *ConfigBuilder) Build() string {
	if b.renderTable {
		var sb strings.Builder
		for _, e := range b.entries {
			switch e.kind {
			case kindComment:
				sb.WriteString("# " + e.text + "\n")
			case kindBlank:
				sb.WriteString("\n")
			}
		}
		sb.WriteString(renderTable(b.entries))
		return sb.String()
	}
	var sb strings.Builder
	active := "__none__"
	for _, e := range b.entries {
		switch e.kind {
		case kindComment:
			sb.WriteString("# " + e.text + "\n")
		case kindBlank:
			sb.WriteString("\n")
		case kindSectionHeader:
			sb.WriteString("[" + e.text + "]\n")
			active = e.section
		case kindKeyval:
			if e.section != active {
				// A root-level key returned to the global scope after a section:
				// close nothing (top-level INI keys are implicit global), just track.
				active = e.section
			}
			sb.WriteString(e.key + b.opts.Separator + e.value + "\n")
		}
	}
	return sb.String()
}

// ConfigSection methods.

// Set adds a key=value line in the section.
func (s *ConfigSection) Set(key string, value any) *ConfigSection {
	s.parent.entries = append(s.parent.entries, configEntry{
		kind: kindKeyval, section: s.section, key: key,
		value: s.parent.format(key, scalar(value)),
	})
	return s
}

// SetIf adds a key=value line in the section only when value is non-empty.
func (s *ConfigSection) SetIf(key string, value string) *ConfigSection {
	if value != "" {
		s.Set(key, value)
	}
	return s
}

// SetFlag adds "key=y" in the section when truthy is true.
func (s *ConfigSection) SetFlag(key string, truthy bool) *ConfigSection {
	if truthy {
		s.parent.entries = append(s.parent.entries, configEntry{
			kind: kindKeyval, section: s.section, key: key, value: "y",
		})
	}
	return s
}

// SetFromEnv adds "key=<env value>" in the section only when set.
func (s *ConfigSection) SetFromEnv(envName, key string) *ConfigSection {
	return s.SetIf(key, EnvGet(envName))
}

// format serializes a key and scalar value, applying the value format.
func (b *ConfigBuilder) format(key, value string) string {
	switch b.opts.ValueFormat {
	case "quote":
		return "'" + value + "'"
	case "auto":
		if autoFormatUnquoted(value) {
			return value
		}
		return "'" + value + "'"
	default:
		return value
	}
}

// autoFormatUnquoted reports whether a value stays bare under "auto".
var autoFormatUnquotedPattern = regexp.MustCompile(`^(?:[0-9]+(?:\.[0-9]+)?(?:kB|MB|GB|TB|ms|s|min|h|d)?|on|off|true|false)$`)

func autoFormatUnquoted(value string) bool {
	return autoFormatUnquotedPattern.MatchString(strings.TrimSpace(value))
}

// renderTable writes 2D rows as space-separated columns, aligned for legibility.
func renderTable(entries []configEntry) string {
	var rows [][]string
	for _, e := range entries {
		if e.kind == kindTable {
			rows = append(rows, e.rows...)
		}
	}
	if len(rows) == 0 {
		return ""
	}
	cols := 0
	for _, r := range rows {
		if len(r) > cols {
			cols = len(r)
		}
	}
	widths := make([]int, cols)
	for _, r := range rows {
		for i, cell := range r {
			if len(cell) > widths[i] {
				widths[i] = len(cell)
			}
		}
	}
	var sb strings.Builder
	for _, r := range rows {
		parts := make([]string, len(r))
		for i, cell := range r {
			if i == len(r)-1 {
				parts[i] = cell
			} else {
				parts[i] = padRight(cell, widths[i])
			}
		}
		sb.WriteString(strings.Join(parts, "  ") + "\n")
	}
	return sb.String()
}

func padRight(s string, n int) string {
	if len(s) >= n {
		return s
	}
	return s + strings.Repeat(" ", n-len(s))
}

// splitRepeat normalizes a value; array values expand to multiple lines.
func splitRepeat(value any) []string {
	switch v := value.(type) {
	case []string:
		return v
	case []any:
		out := make([]string, 0, len(v))
		for _, e := range v {
			out = append(out, scalar(e))
		}
		return out
	default:
		return []string{scalar(value)}
	}
}

// scalar converts a goja value to a string.
func scalar(v any) string {
	switch t := v.(type) {
	case nil:
		return ""
	case string:
		return t
	case bool:
		if t {
			return "true"
		}
		return "false"
	case int:
		return fmt.Sprintf("%d", t)
	case int64:
		return fmt.Sprintf("%d", t)
	case float64:
		return fmt.Sprintf("%v", t)
	default:
		return fmt.Sprintf("%v", v)
	}
}

func asString(v any) string {
	s, _ := v.(string)
	return s
}

// EnvGet reads an environment variable, returning "" when unset/empty.
func EnvGet(name string) string {
	return repository.Get(os.Environ(), name, "")
}

// commentLines flattens a comment spec (string or []string) into lines.
func commentLines(v any) []string {
	switch t := v.(type) {
	case nil:
		return nil
	case string:
		return []string{t}
	case []string:
		return t
	case []any:
		out := make([]string, 0, len(t))
		for _, e := range t {
			out = append(out, scalar(e))
		}
		return out
	default:
		return []string{scalar(v)}
	}
}

// tableRows extracts the rows 2D matrix from a spec.
func tableRows(v any) ([][]string, bool) {
	rows, ok := v.([][]string)
	if ok && len(rows) > 0 {
		return rows, true
	}
	arr, ok := v.([]any)
	if !ok || len(arr) == 0 {
		return nil, false
	}
	out := make([][]string, 0, len(arr))
	for _, r := range arr {
		if ra, ok := r.([]any); ok {
			row := make([]string, len(ra))
			for i, c := range ra {
				row[i] = scalar(c)
			}
			out = append(out, row)
		} else if rs, ok := r.([]string); ok {
			out = append(out, rs)
		}
	}
	return out, len(out) > 0
}

type pair struct {
	name  string
	value any
}

// orderedPairs flattens a properties spec. A Go map yields sorted pairs; an
// array of [key, value] pairs preserves insertion order.
func orderedPairs(v any) ([]pair, bool) {
	if m, ok := v.(map[string]any); ok {
		keys := make([]string, 0, len(m))
		for k := range m {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		out := make([]pair, 0, len(keys))
		for _, k := range keys {
			out = append(out, pair{name: k, value: m[k]})
		}
		return out, true
	}
	arr, ok := v.([]any)
	if !ok {
		return nil, false
	}
	out := make([]pair, 0, len(arr))
	for _, e := range arr {
		if p, ok := e.([]any); ok && len(p) >= 2 {
			out = append(out, pair{name: scalar(p[0]), value: p[1]})
		} else if p, ok := e.([]string); ok && len(p) >= 2 {
			out = append(out, pair{name: p[0], value: p[1]})
		}
	}
	return out, true
}

type sectionSpec struct {
	name  string
	pairs []pair
}

// orderedSections flattens a sections spec. A map of name->props yields sorted
// sections; an array of [name, props] pairs preserves order.
func orderedSections(v any) ([]sectionSpec, bool) {
	if m, ok := v.(map[string]any); ok {
		names := make([]string, 0, len(m))
		for n := range m {
			names = append(names, n)
		}
		sort.Strings(names)
		out := make([]sectionSpec, 0, len(names))
		for _, n := range names {
			pairs, _ := orderedPairs(m[n])
			out = append(out, sectionSpec{name: n, pairs: pairs})
		}
		return out, true
	}
	arr, ok := v.([]any)
	if !ok {
		return nil, false
	}
	out := make([]sectionSpec, 0, len(arr))
	for _, e := range arr {
		if p, ok := e.([]any); ok && len(p) == 2 {
			pairs, _ := orderedPairs(p[1])
			out = append(out, sectionSpec{name: scalar(p[0]), pairs: pairs})
		}
	}
	return out, len(out) > 0
}
