package scriptmodules

import (
	"strings"
	"testing"
)

func TestConfigBuildKeyValue(t *testing.T) {
	m := NewConfigModule()
	out, err := m.Build(map[string]any{
		"comment":     "PostgreSQL configuration generated by container",
		"separator":   " = ",
		"valueFormat": "auto",
		"properties": map[string]any{
			"listen_addresses": "*",
			"port":             5432,
			"shared_buffers":   "256MB",
			"timezone":         "UTC",
		},
	})
	if err != nil {
		t.Fatalf("Build: %v", err)
	}
	for _, want := range []string{
		"# PostgreSQL configuration generated by container",
		"listen_addresses = '*'",
		"port = 5432",
		"shared_buffers = 256MB",
		"timezone = 'UTC'",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("output missing %q\n---\n%s", want, out)
		}
	}
}

func TestConfigBuildTable(t *testing.T) {
	m := NewConfigModule()
	out, err := m.Build(map[string]any{
		"comment": "PostgreSQL Host Based Authentication configuration",
		"rows": []any{
			[]any{"local", "all", "postgres", "trust"},
			[]any{"host", "all", "all", "0.0.0.0/0", "md5"},
			[]any{"host", "all", "all", "::/0", "md5"},
		},
	})
	if err != nil {
		t.Fatalf("Build: %v", err)
	}
	if !strings.HasPrefix(out, "# PostgreSQL Host Based Authentication configuration\n") {
		t.Errorf("table should preserve comment header\n---\n%s", out)
	}
	lines := strings.Split(strings.TrimRight(out, "\n"), "\n")
	if len(lines) != 4 {
		t.Fatalf("expected 4 lines, got %d\n---\n%s", len(lines), out)
	}
	// Header line is the comment; remaining three are aligned rows.
	if !strings.HasPrefix(lines[1], "local  all  postgres  trust") {
		t.Errorf("row 1 unexpected: %q", lines[1])
	}
	if !strings.HasPrefix(lines[2], "host   all  all       0.0.0.0/0  md5") {
		t.Errorf("row 2 unexpected: %q", lines[2])
	}
}

func TestConfigBuildIni(t *testing.T) {
	m := NewConfigModule()
	out, err := m.Build(map[string]any{
		"comment":     "pgBackRest configuration generated by container",
		"separator":   "=",
		"valueFormat": "none",
		"sections": map[string]any{
			"global": map[string]any{
				"repo1-retention-full": "2",
				"log-level-console":    "info",
				"log-path":             "/opt/backup/log",
			},
			"default": map[string]any{
				"pg1-path": "/opt/data",
				"pg1-port": 5432,
			},
		},
	})
	if err != nil {
		t.Fatalf("Build: %v", err)
	}
	for _, want := range []string{
		"# pgBackRest configuration generated by container",
		"[global]",
		"log-level-console=info",
		"log-path=/opt/backup/log",
		"[default]",
		"pg1-path=/opt/data",
		"pg1-port=5432",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("output missing %q\n---\n%s", want, out)
		}
	}
}

func TestConfigBuildOrderedPairs(t *testing.T) {
	m := NewConfigModule()
	// Array of [key, value] pairs preserves insertion order.
	out, err := m.Build(map[string]any{
		"separator":   "=",
		"valueFormat": "auto",
		"properties": []any{
			[]any{"b", 2},
			[]any{"a", 1},
			[]any{"c", 3},
		},
	})
	if err != nil {
		t.Fatalf("Build: %v", err)
	}
	if !strings.HasPrefix(out, "b=2\n") {
		t.Errorf("array pairs should preserve insertion order (b first)\n---\n%s", out)
	}
}

func TestConfigBuilderConditionals(t *testing.T) {
	m := NewConfigModule()
	b := m.Builder(map[string]any{"separator": "=", "valueFormat": "none"})
	b.Comment("pgBackRest configuration generated by container")
	g := b.Section("global")
	g.Set("repo1-retention-full", "2")
	g.SetIf("process-max", "4")      // set
	g.SetIf("repo1-s3-bucket", "")   // skipped
	g.SetFlag("archive-async", true) // -> y
	g.SetFlag("repo1-compression", false)
	st := b.Section("default")
	st.Set("pg1-path", "/opt/data")
	st.SetIf("pg1-password", "")
	out := b.Build()

	for _, want := range []string{
		"[global]",
		"repo1-retention-full=2",
		"process-max=4",
		"archive-async=y",
		"[default]",
		"pg1-path=/opt/data",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("output missing %q\n---\n%s", want, out)
		}
	}
	for _, forbid := range []string{"repo1-s3-bucket", "repo1-compression", "pg1-password"} {
		if strings.Contains(out, forbid) {
			t.Errorf("output should not contain %q\n---\n%s", forbid, out)
		}
	}
}

func TestConfigBuilderRepeatKeys(t *testing.T) {
	m := NewConfigModule()
	b := m.Builder(map[string]any{"separator": " "})
	b.Set("ListenAddress", []string{"0.0.0.0", "::"})
	b.Set("HostKey", []string{"/run/a", "/run/b"})
	out := b.Build()

	for _, want := range []string{
		"ListenAddress 0.0.0.0",
		"ListenAddress ::",
		"HostKey /run/a",
		"HostKey /run/b",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("output missing %q\n---\n%s", want, out)
		}
	}
}

func TestConfigBuilderBlankComment(t *testing.T) {
	m := NewConfigModule()
	b := m.Builder(map[string]any{"separator": "="})
	b.Comment("header")
	b.Blank()
	b.Set("a", "1")
	b.Comment("sub header")
	b.Set("b", "2")
	out := b.Build()
	if !strings.Contains(out, "# header\n\na=1\n# sub header\nb=2") {
		t.Errorf("unexpected output\n---\n%s", out)
	}
}
